#!/usr/bin/env python3

from argparse import ArgumentParser
from mmap import ACCESS_READ, mmap
from os import _exit, fsync, path
from random import random
from signal import SIGHUP, SIGINT, SIGQUIT, SIGTERM, signal
from sys import exit, stdout
from time import monotonic


def log(*msg):
    """
    """
    print(*msg)
    if separate_log:
        logging.info(*msg)


def signal_handler(signum, frame):
    """
    """
    def signal_handler_inner(signum, frame):
        pass

    for i in sig_list:
        signal(i, signal_handler_inner)

    log('got signal {}'.format(signum))
    stdout.flush()
    _exit(0)


def writer():
    """
    """
    STRING_MIB = '\n' * M

    log('starting cache-bench')
    log('  file: {}'.format(f_path))
    log('  file size: {} MiB'.format(w_num))
    log('writing the file...')

    with open(f_path, 'w') as f:
        for _ in range(w_num):
            f.write(STRING_MIB)
        log('fsync...')
        fsync(f.fileno())
    log('OK')
    exit()


def prereadf(f_size):
    """
    """
    log('prereading (caching) the file...')

    with open(f_path, 'rb') as f:
        if mapped:
            f = mmap(f.fileno(), 0, access=ACCESS_READ)

        r_size = 0
        pm_start = monotonic()
        pm_old = pm_start

        while True:
            r_len = len(f.read(M))
            pm_new = monotonic()
            r_size += r_len

            if pm_new - pm_old > interval:
                pm_old = pm_new
                log('  preread {} MiB ({}%) in {}s'.format(
                    round(r_size / M, 1),
                    round(r_size / f_size * 100, 1),
                    round(pm_new - pm_start, 1)))

            if r_len == 0:
                log('  preread {} MiB ({}%) in {}s'.format(
                    round(r_size / M, 1),
                    round(r_size / f_size * 100, 1),
                    round(pm_new - pm_start, 1)))
                break


def reader():
    """
    """
    log('starting cache-bench')
    f_size = path.getsize(f_path)

    log('  file: {}'.format(f_path))
    log('  file size: {} MiB'.format(round(f_size / M, 1)))

    if f_size == 0:
        log('the file has zero size, nothing to read!')
        exit(1)

    if separate_log:
        log('  log file: {}'.format(log_file))
    else:
        log('  log file is not set')

    log('  output interval: {}s'.format(interval))
    log('  mmap: {}, preread: {}, bloat: {}, chunk: {} KiB'.format(
        m_map, pre_read, bloat, chunk))

    if preread:
        prereadf(f_size)

    with open(f_path, 'rb') as f:

        if mapped:
            f = mmap(f.fileno(), 0, access=ACCESS_READ)

        log('reading {} MiB from the file...'.format(r_num))

        if bloating:
            with open('/proc/self/oom_score_adj', 'w') as self_oom_score_adj:
                self_oom_score_adj.write('1000\n')

        if bloating:
            ex_list = []

        r_size = 0
        t0 = monotonic()
        t_old = t0
        s_old = 0

        while True:
            f.seek(int(f_size * random()))
            ch = f.read(CHUNK)
            r_size += len(ch)

            if bloating:
                ex_list.append(ch)

            t = monotonic()
            dt = t - t_old
            if dt >= interval:

                d_s = r_size - s_old
                t_old = t
                s_old = r_size
                dt0 = t - t0
                log('  read {}M in {}s ({}M/s); total {}M in {}s, avg '
                    '{}M/s'.format(
                        round(d_s / M, 1),
                        round(dt, 1),
                        round(d_s / M / dt, 1),
                        round(r_size / M, 1),
                        round(dt0, 1),
                        round(r_size / M / dt0, 1)
                    ))

            if r_size >= r_bytes:

                d_s = r_size - s_old
                t_old = t
                s_old = r_size
                dt0 = t - t0
                log('  read {}M in {}s ({}M/s); total {}M in {}s, avg '
                    '{}M/s'.format(
                        round(d_s / M, 1),
                        round(dt, 1),
                        round(d_s / M / dt, 1),
                        round(r_size / M, 1),
                        round(dt0, 1),
                        round(r_size / M / dt0, 1)
                    ))

                ddt = monotonic() - t0
                log('total read {} MiB in {}s (avg {} MiB/s)'.format(
                    round(r_size / M, 1),
                    round(ddt, 1),
                    round(r_size / M / ddt, 1)
                ))
                stdout.flush()
                _exit(0)


parser = ArgumentParser()

parser.add_argument(
    '-f',
    '--file',
    help='path to the file to be read or written',
    default='testfile.bench',
    type=str
)

parser.add_argument(
    '-r',
    '--read',
    help='how many mebibytes to read from the file',
    default=0,
    type=float
)

parser.add_argument(
    '-w',
    '--write',
    help='size of the file being written',
    default=0,
    type=int
)

parser.add_argument(
    '-m',
    '--mmap',
    help='mmap the file (0 | 1)',
    default=0,
    type=int
)

parser.add_argument(
    '-p',
    '--preread',
    help='preread the file (0 | 1)',
    default=0,
    type=int
)

parser.add_argument(
    '-b',
    '--bloat',
    help='bloat process memory (0 | 1)',
    default=0,
    type=int
)

parser.add_argument(
    '-c',
    '--chunk',
    help='chunk size in KiB',
    default=64,
    type=int
)

parser.add_argument(
    '-i',
    '--interval',
    help='output interval in seconds',
    default=2,
    type=float
)

parser.add_argument(
    '-l',
    '--log',
    help='path to the log file',
    default=None,
    type=str
)

args = parser.parse_args()

f_path = args.file
r_num = args.read
w_num = args.write
m_map = args.mmap
pre_read = args.preread
bloat = args.bloat
chunk = args.chunk
interval = args.interval
log_file = args.log

if log_file is None:
    separate_log = False
else:
    separate_log = True

    import logging

    try:
        logging.basicConfig(
            filename=log_file,
            level=logging.INFO,
            format="%(asctime)s: %(message)s")
    except Exception as e:
        print(e)
        exit(1)

if m_map == 0:
    mapped = False
elif m_map == 1:
    mapped = True
else:
    log('invalid --mmap value')
    exit(1)

if pre_read == 0:
    preread = False
elif pre_read == 1:
    preread = True
else:
    log('invalid --preread value')
    exit(1)

if bloat == 0:
    bloating = False
elif bloat == 1:
    bloating = True
else:
    log('invalid --bloat value')
    exit(1)

if chunk <= 0:
    log('invalid --chunk value')
    exit(1)

if interval < 0:
    log('invalid --interval value')
    exit(1)


K = 1024
M = K**2
r_bytes = int(M * r_num)
CHUNK = K * chunk

sig_list = [SIGTERM, SIGINT, SIGQUIT, SIGHUP]

for i in sig_list:
    signal(i, signal_handler)


if w_num > 0:

    if path.exists(f_path):
        log('"{}" already exists'.format(f_path))
        exit(1)

    try:
        with open(f_path, 'wb') as f:
            f.write(b'')
    except Exception as e:
        log(e)
        exit(1)

    writer()

if r_num > 0:

    try:
        with open(f_path, 'rb') as f:
            f.read(1)
    except Exception as e:
        log(e)
        exit(1)

    reader()

log('set correct --read or --write value')

exit(1)
